fix: potential inconsistent conditional result types (#179)
<!--
  ~ Copyright 2023 StreamNative, Inc.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
-->

<!--
### Contribution Checklist

- Fill out the template below to describe the changes contributed by the
pull request. That will give reviewers the context they need to do the
review.
  
- Each pull request should address only one issue, not mix up code from
multiple issues.
  
  - Each commit in the pull request has a meaningful commit message

- Once all items of the checklist are addressed, remove the above text
and this checklist, leaving only the filled out template below.

**(The sections below can be removed for hotfixes of typos)**
-->


### Motivation

```
Error: Inconsistent conditional result types

 156:   node_groups = var.enable_v3_node_migration ? merge(local.v3_node_groups, local.v2_node_groups) : var.enable_v3_node_groups ? local.v3_node_groups : local.v2_node_groups
    ├────────────────
    │ local.v2_node_groups is object with 15 attributes
    │ local.v3_node_groups is object with 1 attribute "snc-core"
    │ var.enable_v3_node_groups is true

The true and false result expressions must have consistent types. The 'true'
value includes object attribute "snc-core", which is absent in the 'false'
value.
```

### Modifications

- Make the definitions of v2_node_groups and v3_node_groups themselves
conditional, so they result in an empty map ({}) when not in use. This
ensures type consistency. Then simplify the definition of node_groups to
a simple merge of the two, as they will correctly be either populated or
empty based on the variable flags.

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### Documentation

- [x] `no-need-doc`

Signed-off-by: Max Xu <xuhuan@live.cn>